name: Jira Sync
on:
  push:
    branches:
      - 'TEST-*'
      - 'KAN-*'
  pull_request:
    types: [opened, closed]

jobs:
  update-jira:
    runs-on: ubuntu-latest
    steps:
      - name: Extract issue key from branch
        id: extract-key
        run: |
          if [[ "${{ github.ref }}" =~ refs/heads/(TEST-[0-9]+|KAN-[0-9]+) ]]; then
            echo "issue_key=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
          elif [[ "${{ github.head_ref }}" =~ (TEST-[0-9]+|KAN-[0-9]+) ]]; then
            echo "issue_key=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
          fi

      - name: Test Jira API with proper encoding
        if: steps.extract-key.outputs.issue_key
        run: |
          echo "Testing API call for: ${{ steps.extract-key.outputs.issue_key }}"
          
          curl -u "${{ secrets.JIRA_USER_EMAIL }}:${{ secrets.JIRA_API_TOKEN }}" \
            -H "Accept: application/json" \
            "${{ secrets.JIRA_BASE_URL }}/rest/api/3/issue/${{ steps.extract-key.outputs.issue_key }}/transitions"

      - name: Update Jira on push
        if: github.event_name == 'push' && steps.extract-key.outputs.issue_key
        run: |
          echo "Transitioning ${{ steps.extract-key.outputs.issue_key }} to IN PROGRESS"
          curl -u "${{ secrets.JIRA_USER_EMAIL }}:${{ secrets.JIRA_API_TOKEN }}" \
            -X POST \
            -H "Accept: application/json" \
            -H "Content-Type: application/json" \
            -d '{"transition":{"id":"21"}}' \
            "${{ secrets.JIRA_BASE_URL }}/rest/api/3/issue/${{ steps.extract-key.outputs.issue_key }}/transitions"