name: Jira Sync
on:
  push:
    branches:
      - 'TEST-*'
      - 'KAN-*'
  pull_request:
    types: [opened, closed]

jobs:
  update-jira:
    runs-on: ubuntu-latest
    steps:
      - name: Extract issue key from branch
        id: extract-key
        run: |
          if [[ "${{ github.ref }}" =~ refs/heads/(TEST-[0-9]+|KAN-[0-9]+) ]]; then
            echo "issue_key=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
          elif [[ "${{ github.head_ref }}" =~ (TEST-[0-9]+|KAN-[0-9]+) ]]; then
            echo "issue_key=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
          fi

      - name: Debug and test Jira API
        if: steps.extract-key.outputs.issue_key
        run: |
          echo "Issue key: ${{ steps.extract-key.outputs.issue_key }}"
          echo "Base URL: ${{ secrets.JIRA_BASE_URL }}"
          echo "Email: ${{ secrets.JIRA_USER_EMAIL }}"

          AUTH=$(echo -n "${{ secrets.JIRA_USER_EMAIL }}:${{ secrets.JIRA_API_TOKEN }}" | base64)
          
          echo "Making API call..."
          curl -v -H "Authorization: Basic $AUTH" \
            "${{ secrets.JIRA_BASE_URL }}/rest/api/3/issue/${{ steps.extract-key.outputs.issue_key }}/transitions" \
            2>&1 || echo "Curl failed with code $?"